gadgetsphere/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("marketplace.urls"))
]

marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name='login'),
    path("logout/", views.logout_view, name='logout'),
    path("product/<int:prod_id>/", views.products, name='product'),
    path("cart/", views.cart, name='cart'),
    path("checkout/", views.checkout, name='checkout'),
    path("wishlist/", views.wishlist, name='wishlist')
]

marketplace/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=25, null=True)
    category = models.CharField(max_length=25, null=True)
    img_url = models.TextField(null=True)
    description = models.TextField(null=True)
    price = models.FloatField(null=True)
    stock_amt = models.IntegerField(null=True)
    brand = models.CharField(max_length=25, null=True)

class Cart(models.Model):
    prod_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_cart')
    username = models.CharField(max_length=25)

class Wishlist(models.Model):
    prod_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_wish')
    username = models.CharField(max_length=25)

marketplace/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.urls import reverse
from django.views.decorators.cache import cache_control
from .models import Product, Cart, Wishlist
from django.contrib import messages

# Create your views here.

def register(request):
    if request.method == 'GET':
        return render(request, "marketplace/register.html")
    else:
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return HttpResponse("Passwords must match")
        
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return HttpResponse("Username Taken")
        
        return HttpResponseRedirect(reverse('marketplace:login'))

def login_view(request):
    if request.method == 'GET':
        return render(request, "marketplace/login.html")
    else:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("marketplace:index"))
        else:
            return HttpResponse("ERROR")

# @cache_control(no_cache=True, must_revalidate=True)
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("marketplace:index"))

# @login_required(login_url='/login')
# @cache_control(no_cache=True, must_revalidate=True)
def index(request):
    products = list(Product.objects.all())
    return render(request, "marketplace/homepage.html", {
        "products":products
    })


def products(request, prod_id):
    if request.method == 'GET':
        product_info = list(Product.objects.filter(id=prod_id))
        return render(request, "marketplace/product.html", {"products": product_info})
    if request.method == 'POST':
        prod_id = request.POST.get('prods_id')
        action = request.POST.get('action')
        prod_check = Cart.objects.filter(prod_id=prod_id).filter(username=request.user.username)
        if action == "0":
            prod_obj = Product.objects.get(id=prod_id)
            if len(prod_check) == 0:
                cart = Cart(prod_id=prod_obj, username = request.user.username)
                cart.save()
                messages.success(request, 'Added to Cart Successfully')
                return HttpResponseRedirect(reverse('marketplace:product', kwargs={'prod_id': prod_id}))
            else:
                messages.error(request, 'Item already exists in cart')
                return HttpResponseRedirect(reverse('marketplace:product', kwargs={'prod_id': prod_id}))
        else:
            cart_del = Cart.objects.get(prod_id=prod_id, username=request.user.username)
            cart_del.delete()
            messages.success(request, 'Removed from cart successfully')
            return HttpResponseRedirect(reverse('marketplace:cart'))
            

@login_required(login_url='/login')
def cart(request):
    if request.method == 'GET':
        user = request.user.username
        user_cart = list(Cart.objects.filter(username=user))
        return render(request, "marketplace/cart.html", {
            "products": user_cart
        })

@login_required(login_url='/login')
def checkout(request):
    if request.method == 'GET':
        user = request.user.username
        user_cart = list(Cart.objects.filter(username=user))
        total = 0
        for i in range(len(user_cart)):
            total += user_cart[i].prod_id.price
        return render(request, "marketplace/checkout.html", {
            "products": user_cart,
            "totals": total
        })


def wishlist(request):
    if request.method == 'GET':
        user = request.user.username
        user_wish = list(Wishlist.objects.filter(username=user))
        return render(request, "marketplace/wishlist.html", {
            "products": user_wish
        })
    else:
        id = request.POST.get('prods_id')
        action = request.POST.get('action')
        if action == "1":
            wish_del = Wishlist.objects.get(prod_id=id, username=request.user.username)
            wish_del.delete()
            messages.success(request, 'Removed from wishlist successfully')
            return HttpResponseRedirect(reverse('marketplace:product', kwargs={'prod_id': id}))
        else:
            prod_check = Wishlist.objects.filter(prod_id=id).filter(username=request.user.username)
            if len(prod_check) == 0:
                prod_obj = Product.objects.get(id=id)
                wish = Wishlist(prod_id=prod_obj, username=request.user.username )
                wish.save()
                messages.success(request, 'Added to Wishlist Successfully')
                return HttpResponseRedirect(reverse('marketplace:product', kwargs={'prod_id': id}))
            else:
                messages.error(request, 'Item already exists in wishlist')
                return HttpResponseRedirect(reverse('marketplace:product', kwargs={'prod_id': id}))

marketplace/templates/marketplace/cart.html
{% extends "marketplace/layout.html" %}

{% block body %}
{% load static %}
    <h1 style="text-align: center;">Your Cart</h1>
    <br>
    <div class="container">
        
        <div class="row">
            {% for product in products %}
            <div class="col-4" style="padding: 10px;">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{ product.prod_id.title }}</h5>
                      <h6 class="card-subtitle mb-2 text-muted">{{ product.prod_id.category }}</h6>
                      <b>Price: ₹ {{ product.prod_id.price }}</b>
                      <br>
                      <form action="{% url 'marketplace:product' product.prod_id.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ product.prod_id.id }}" name="prods_id">
                        <input type="hidden" value="1" name="action">
                        <input type="submit" class="btn btn-link" value="Remove from cart">
                      </form>
                    </div>
                  </div>
            </div>
            {% endfor %}
            <br>
            {% if messages %}
            {% for message in messages %}
            {% if message.tags %}
            <br>
            <div class="alert alert-primary" role="alert">
                {{ message.message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
        <br>
        <div>
            <a href="{% url 'marketplace:checkout' %}" class="btn btn-info">Proceed to Checkout</a>
        </div>
        

    </div>
    
{% endblock %}

marketplace/templates/marketplace/checkout.html
{% extends "marketplace/layout.html" %}

{% block body %}
{% load static %}

<h1 class="headings">Thank you for shopping with GadgetSphere!</h1>
<br>
<div>
    <h3>Your Bill:</h3>
    <ol>
        {% for product in products %}
        <b><li>{{ product.prod_id.title }} - ₹ {{ product.prod_id.price }}</li></b>
        {% endfor %}
    </ol>
    <br>
    <h3>Total Amount: ₹ {{ totals }}</h3>
</div>

{% endblock %}

marketplace/templates/marketplace/homepage.html
{% extends "marketplace/layout.html" %}

{% block body %}
{% load static %}
    <div style="text-align: center;">
        <h1 class="headings">Welcome to GadgetSphere</h1>
        <h2 class="headings">The No 1. Marketplace for Electronics</h2>
        <br>
        <h3 class="headings">Check out our exciting range!</h3>
    </div>
    
    <br>
    <div class="container" id="prod_cont" style="text-align: center; align-content: center;">
        <div class="row d-flex justify-content-center" style="align-items: center;">
            {% for producty in products %}
                <a href="{% url 'marketplace:product' producty.id %}">
                    <div class="col-4" style="padding: 25px;">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="{{ producty.img_url }}" alt="Card image cap">
                            <div class="card-body">
                              <h5 class="card-title">{{ producty.title }}</h5>
                              <p class="card-text">₹ {{ producty.price }}</p>
                            </div>
                        </div>
                    </div>
                </a>
                <br>
            {% endfor %}
        </div>
    </div>

{% endblock %}

marketplace/templates/marketplace/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'marketplace/homepage.css' %}">
    <title>Document</title>
    {% block script %}
    {% endblock %}
</head>
<body style="padding: 10px;">
    <h1><a href="{% url 'marketplace:index' %}">GadgetSphere</a></h1>
    {% if user.is_authenticated %}
        Signed in as <b>{{ user.username }}</b>
    {% else %}
        <b>Not Signed In</b>
    {% endif %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:cart' %}">Your Cart</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:checkout' %}">Checkout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:wishlist' %}">Wishlist</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'marketplace:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'marketplace:login' %}">Log In</a>
            </li>
            {% endif %}
        </ul>
        
    </nav>
    <br>
    {% block body %}
    {% endblock %}
</body>
</html>

marketplace/templates/marketplace/login.html
{% extends "marketplace/layout.html" %}

{% block body %}
<h1>Login</h1>
    <br>
    <form action="{% url 'marketplace:login' %}" method="post">
        {% csrf_token %}
        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        <br>
        <input class="form-control" type="password" name="password" placeholder="Password">
        <br>
        <input class="btn btn-primary" type="submit" value="Login">
        <br>
        <p>Don't have an account?<a href="{% url 'marketplace:register' %}" class="btn btn-link">Register Here</a></p>
    </form>
{% endblock %}

marketplace/templates/marketplace/product.html
{% extends 'marketplace/layout.html' %}

{% load static %}
{% block script %}
    <script src="{% static 'marketplace/product.js' %}"></script>
{% endblock %}

{% block body %}
{% for producty in products %}
    <h1>{{ producty.title }}</h1>
    <br>
    <img src="{{ producty.img_url }}" style="width: 300px; height: 300px;">
    <br>
    <b>Category: {{ producty.category }}</b>
    <br>
    <p>{{ producty.description }}</p>
    <br>
    <h3><b>Price: ₹ {{ producty.price }}</b></h3>
    <br>
    {% if user.is_authenticated %}
        <form action="{% url 'marketplace:product' producty.id%}" method="post" id="cart_form">
            {% csrf_token %}
            <input type="hidden" id="prod_id" value="{{ producty.id }}" name="prods_id">
            <input type="hidden" id="action" value="0" name="action">
            <input type="submit" class="btn btn-primary" value="Add to Cart">
        </form>
        <br>
        <form action="{% url 'marketplace:wishlist' %}" method="post" id="wish_form">
            {% csrf_token %}
            <input type="hidden" id="prod_id" value="{{ producty.id }}" name="prods_id">
            <input type="hidden" value="0" name="action">
            <input type="submit" class="btn btn-primary" value="Add to Wishlist">
        </form>
    {% endif %}
    
    <br>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}
    <br>
    <div class="alert alert-primary" role="alert">
        {{ message.message }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    
{% endfor %}
    
{% endblock %}

marketplace/templates/marketplace/register.html
{% extends "marketplace/layout.html" %}

{% block body %}
    <h1>Register</h1>
    <br>
    <form action="{% url 'marketplace:register' %}" method="post">
        {% csrf_token %}
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        <br>
        <input class="form-control" type="email" name="email" placeholder="Email Address">
        <br>
        <input class="form-control" type="password" name="password" placeholder="Password">
        <br>
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        <br>

        <input class="btn btn-primary" type="submit" value="Register">
        <br>
        <p>Already have an account?<a href="{% url 'marketplace:login' %}" class="btn btn-link">Log In</a>here.</p>
    </form>
    <br>
    
{% endblock %}






<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <h1>Register</h1>
    <br>
    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
        <input class="form-control" type="password" name="password" placeholder="Password">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">

        <input class="btn btn-primary" type="submit" value="Register">
    </form>
</body>
</html> -->

marketplace/templates/marketplace/wishlist.html
{% extends "marketplace/layout.html" %}

{% block body %}
{% load static %}

<h1 style="text-align: center;">Your Wishlist</h1>
<br>
<div class="container">
    <div class="row">
        {% for product in products %}
            <div class="col-4" style="padding: 10px;">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{ product.prod_id.title }}</h5>
                      <h6 class="card-subtitle mb-2 text-muted">{{ product.prod_id.category }}</h6>
                      <b>Price: ₹ {{ product.prod_id.price }}</b>
                      <br>
                      <form action="{% url 'marketplace:wishlist' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ product.prod_id.id }}" name="prods_id">
                        <input type="hidden" value="1" name="action">
                        <input type="submit" class="btn btn-link" value="Remove from wishlist">
                      </form>
                    </div>
                  </div>
            </div>
            {% endfor %}
    </div>
</div>

{% endblock %}